### ISSUE TITLE
Improve VM support

### ISSUE THREAD

**Issue by johnsca** [canonical/github-runner-operator#12]
Currently, a given deployment can only have either LXD runners or VM runners, but not a mix of both. The config would need to change to support it, but the logic is mostly in place already and it would make managing mixed sets of runners much easier.

**Comment by r-f-g** [comment]
@ijansky @addyess This problem was solved by PR #18, right?

However, I tried to use VM in github-runner and they are unusable due to low resources. VMs are created with 1 cpu and 1GB ram. Can we add `limits.cpu=4` and `limits.memory=8GiB` to `runner` profile, or add them as a config option?

**Comment by addyess** [comment]
So, does the github runner really need a huge beefy machine to run a little node script?  I suppose the work being asked of the VM may be intense -- which kinda makes you wonder if the test environment should spawn a larger VM to do the dirty work

Here are the docs for github hosted runners:
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

> Hardware specification for Windows and Linux virtual machines:
> 2-core CPU
> 7 GB of RAM memory
> 14 GB of SSD disk space

Do you suppose these specs would serve as a better default in the VM profile?

I support `limits.cpu=2` and `limits.memory=7GiB`.  is this fair?

**Comment by r-f-g** [comment]
I think if we want to run `microk8s` or `microstack` on these runners, then we need a bigger VM.
`microstack` is recommended to be used with a multi-core cpu, 8 GB RAM and 100 GB disk space according to [doc](https://ubuntu.com/tutorials/install-openstack-on-your-workstation-and-launch-your-first-instance#1-overview).
`microk8s` is recommended to be used with 4 GB RAM and 20 GB disk space according to [doc](https://microk8s.io/docs/getting-started).

I understand that in CI it doesn't make much sense to always have huge VMs, but this is only used to run functional tests, so I see potential there. At least if I want to have those runners just for a specific repo, it should be up to me to decide on the size of those VMs.
Because of this, I think that these values could be configurable via config options.

**Comment by addyess** [comment]
cool, this is reasonable. can you raise a PR to address it?

**Comment by r-f-g** [comment]
Yes, sure.

**Comment by r-f-g** [comment]
Now I think that this issue could be closed. What do you think @addyess?

**Comment by addyess** [comment]
yeah, super job
